[package]
name = "monkey-typer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
ctrlc = "3.4.5"
env_logger = "0.11.5"
log = "0.4.22"
rdev = "0.5.3"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"

[[bin]]
name = "monkey-typer"
path = "src/main.rs"
